### ISSUE TITLE
Is tomcat 9 supported?

### ISSUE THREAD

**Issue by samene** [OpenIdentityPlatform/OpenAM-JEE-Agents#15]
`[08/30/2021 08:26:20:062 BST] TomcatVersionValidator.getTomcatVersion() - validating ServerInfo:Server version: Apache Tomcat/9.0.41
Server built:   Dec 3 2020 11:43:00 UTC
Server number:  9.0.41.0
OS Name:        Linux
OS Version:     3.10.0-1160.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_152-b16
JVM Vendor:     Azul Systems, Inc.

[08/30/2021 08:26:20:062 BST] TomcatVersionValidator.getTomcatVersion() - version:9.0.41.0 found version: null
[08/30/2021 08:26:20:062 BST] OpenAM Tomcat Agent does not support this tomcat server version
[08/30/2021 08:26:20:062 BST] Interaction failed to continue since one or more of the validators failed.
[08/30/2021 08:26:20:062 BST] InstallHandler: Failed to process install request
[ProductInstallException Stack]
com.sun.identity.install.tools.configurator.InstallException: Invalid directory specified for the $CATALINA_HOME environment variable
        at com.sun.identity.install.tools.configurator.UserDataInteraction.interactSilent(UserDataInteraction.java:114)
        at com.sun.identity.install.tools.configurator.InteractionsRunnerBase.runInteraction(InteractionsRunnerBase.java:157)
        at com.sun.identity.install.tools.configurator.InteractionsRunnerBase.runInteractions(InteractionsRunnerBase.java:96)
        at com.sun.identity.install.tools.configurator.Driver.executeInstanceInteractions(Driver.java:132)
        at com.sun.identity.install.tools.configurator.Driver.executeAllInteractions(Driver.java:76)
        at com.sun.identity.install.tools.configurator.InstallDriver.install(InstallDriver.java:82)
        at com.sun.identity.install.tools.handler.InstallHandler.handleRequest(InstallHandler.java:75)
        at com.sun.identity.install.tools.admin.AdminTool.dispatch(AdminTool.java:232)
        at com.sun.identity.install.tools.admin.AdminTool.run(AdminTool.java:135)
        at com.sun.identity.install.tools.launch.AdminToolLauncher.launchAdminTool(AdminToolLauncher.java:201)
        at com.sun.identity.install.tools.launch.AdminToolLauncher.main(AdminToolLauncher.java:295)
[08/30/2021 08:26:20:064 BST] Exiting with code: 0
`

**Comment by deftdawg** [comment]
```Invalid directory specified for the $CATALINA_HOME environment variable```

Looks like it failed to install whatever it was trying because you didn't set `CATALINA_HOME` in the `env`

**Comment by starkgate** [comment]
I tried running the agentAdmin without `--useResponse`:

```
/opt/j2ee_agents/tomcat_v6_agent/bin/agentadmin --install --acceptLicense
```

This prompts the tool to ask for the environment variables it usually gets from the response.txt file, and gives a bit more debugging information. The issue here is that Tomcat 9 is simply not supported: `OpenAM Tomcat Agent does not support this tomcat server version`.

Complete log:
```
************************************************************************
Welcome to the OpenAM Policy Agent for Apache Tomcat 6.0 Servlet/JSP
Container

************************************************************************

...

$CATALINA_HOME environment variable is the root of the tomcat
installation.
[ ? : Help, < : Back, ! : Exit ]
Enter the $CATALINA_HOME environment variable: /opt/liferay/tomcat-9.0.73

Invalid directory specified for the $CATALINA_HOME environment variable
OpenAM Tomcat Agent does not support this tomcat server version

$CATALINA_HOME environment variable is the root of the tomcat
installation.
[ ? : Help, < : Back, ! : Exit ]
Enter the $CATALINA_HOME environment variable: 
```

**Comment by lscorcia** [comment]
It is supported now, but you have to build the project yourself, there's no release yet. We are using it in production with no issues.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM-JEE-Agents/suites/17878425269/artifacts/1026386984
