### ISSUE TITLE
Error while activating Tomcat agent

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM-JEE-Agents#21]
Hi, we just tested the latest build and we get the following error while triggering an auth:

20-Sep-2023 12:48:56.360 SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
java.lang.NoClassDefFoundError: org/forgerock/openam/session/service/access/SessionPersistenceObservable
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
at org.forgerock.openam.session.SessionCuller.willExpire(SessionCuller.java:122)
at org.forgerock.openam.session.SessionCuller.scheduleToTimerPool(SessionCuller.java:102)
at org.forgerock.openam.session.SessionCuller.<init>(SessionCuller.java:65)
at org.forgerock.openam.session.SessionCache.writeSession(SessionCache.java:132)
at org.forgerock.openam.session.SessionCache.getSession(SessionCache.java:269)
at com.iplanet.sso.providers.dpro.SSOProviderImpl.createSSOToken(SSOProviderImpl.java:206)
at com.iplanet.sso.providers.dpro.SSOProviderImpl.createSSOToken(SSOProviderImpl.java:185)
at com.sun.identity.authentication.AuthContext.getSSOToken(AuthContext.java:1482)
at com.sun.identity.agents.common.ApplicationSSOTokenProvider.getApplicationSSOToken(ApplicationSSOTokenProvider.java:75)
at com.sun.identity.agents.arch.AgentConfiguration.setAppSSOToken(AgentConfiguration.java:619)
at com.sun.identity.agents.arch.AgentConfiguration.bootStrapClientConfiguration(AgentConfiguration.java:725)
at com.sun.identity.agents.arch.AgentConfiguration.initializeConfiguration(AgentConfiguration.java:1147)
at com.sun.identity.agents.arch.AgentConfiguration.<clinit>(AgentConfiguration.java:1586)
at com.sun.identity.agents.arch.Manager.<clinit>(Manager.java:675)
at com.sun.identity.agents.tomcat.v6.AmTomcatRealm.<clinit>(AmTomcatRealm.java:67)

**Comment by maximthomas** [comment]
Try to rebuild with the latest OpenAM snapshot OpenIdentityPlatform/OpenAM#638

**Comment by lscorcia** [comment]
I can confirm this build fixes the issue! Thank you!
